"""Configuration loading, validation, and initialization.

Loads settings from .env file and environment variables.
Environment variables always override .env file values.
"""

import os
from pathlib import Path
from typing import Any

from dotenv import dotenv_values
from platformdirs import user_config_dir


class ConfigError(Exception):
  """Raised when required configuration is missing or invalid."""


# Config keys with their env var names, defaults, and whether required
_CONFIG_SCHEMA: list[tuple[str, str, Any, bool]] = [
  # (config_key, env_var, default, required)
  ("openai_api_key", "OPENAI_API_KEY", None, True),
  ("anthropic_api_key", "ANTHROPIC_API_KEY", None, True),
  ("audio_device", "AUDIO_DEVICE", None, False),
  ("transcription_language", "TRANSCRIPTION_LANGUAGE", "zh", False),
  ("transcription_engine", "TRANSCRIPTION_ENGINE", "openai", False),
  ("summary_model", "SUMMARY_MODEL", "claude-sonnet-4-20250514", False),
]

_ENV_TEMPLATE = """\
# Meeting Transcriber Configuration
# Generated by `mt setup`. Edit values below.

# Required: API keys
OPENAI_API_KEY=
ANTHROPIC_API_KEY=

# Optional: Audio input device name (leave empty for system default)
AUDIO_DEVICE=

# Optional: Transcription settings
TRANSCRIPTION_LANGUAGE=zh
TRANSCRIPTION_ENGINE=openai

# Optional: Summary model
SUMMARY_MODEL=claude-sonnet-4-20250514
"""


def get_config_dir() -> Path:
  """Return the platform-appropriate config directory for meeting-transcriber."""
  return Path(user_config_dir("meeting-transcriber"))


def load_config(*, config_dir: Path | None = None) -> dict[str, Any]:
  """Load configuration from .env file and environment variables.

  Environment variables always take precedence over .env file values.

  Args:
    config_dir: Override config directory (useful for testing).

  Returns:
    Dictionary with configuration values.

  Raises:
    ConfigError: If required keys are missing.
  """
  if config_dir is None:
    config_dir = get_config_dir()

  env_file = config_dir / ".env"
  file_values = dotenv_values(env_file) if env_file.exists() else {}

  config: dict[str, Any] = {}
  missing: list[str] = []

  for config_key, env_var, default, required in _CONFIG_SCHEMA:
    # Environment variables override .env file values
    value = os.environ.get(env_var) or file_values.get(env_var) or None
    if value is None and required:
      missing.append(env_var)
    config[config_key] = value if value is not None else default

  if missing:
    keys_str = ", ".join(missing)
    raise ConfigError(
      f"Missing required config: {keys_str}. "
      f"Run `mt setup` to create a config template, then fill in the values."
    )

  return config


def init_config(*, config_dir: Path | None = None) -> Path:
  """Create config directory and .env template if they don't exist.

  Args:
    config_dir: Override config directory (useful for testing).

  Returns:
    Path to the config directory.
  """
  if config_dir is None:
    config_dir = get_config_dir()

  config_dir.mkdir(parents=True, exist_ok=True)

  env_file = config_dir / ".env"
  if not env_file.exists():
    env_file.write_text(_ENV_TEMPLATE)

  return config_dir
